ebot: 
  image: egguy/ebot-csgo
  ports: 
    - "172.17.0.1:12360:12361"
  links:
    - "mysql:mysql"
    #- "ebotweb:ebotweb"
ebotweb: 
  image: egguy/ebot-csgo-web
  links: 
    - "mysql:mysql"
  ports: 
    - "8081:80"
mysql: 
  ports: 
    - "3306:3306"
  environment: 
    - MYSQL_DATABASE=ebotv3
    - MYSQL_USER=ebotv3
    - MYSQL_PASSWORD=ebotv3
    - MYSQL_ROOT_PASSWORD=ebotv3
  image: mysql
